"""ai routing: ai_accounts + ai_models

Creates the admin-controlled AI routing tables (OmniRoute account pool, fallback
providers, and the user-facing model catalog). Incremental migration — the rest
of the schema is still provisioned via scripts.init_db (create_all) until a full
baseline is autogenerated.

Revision ID: 0001_ai_routing
Revises:
Create Date: 2026-06-17
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "0001_ai_routing"
down_revision = "0000_baseline"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "ai_accounts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("kind", sa.String(length=20), server_default="omniroute", nullable=False),
        sa.Column("base_url", sa.String(length=300), nullable=False),
        sa.Column("api_key", sa.Text(), nullable=False),
        sa.Column("modality", sa.String(length=10), server_default="text", nullable=False),
        sa.Column("tier", sa.Integer(), server_default="0", nullable=False),
        sa.Column("priority", sa.Integer(), server_default="100", nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default=sa.true(), nullable=False),
        sa.Column("status", sa.String(length=12), server_default="active", nullable=False),
        sa.Column("cooldown_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("total_requests", sa.Integer(), server_default="0", nullable=False),
        sa.Column("total_errors", sa.Integer(), server_default="0", nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.String(length=300), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_ai_accounts_tier_priority", "ai_accounts", ["tier", "priority"])

    op.create_table(
        "ai_models",
        sa.Column("key", sa.String(length=40), nullable=False),
        sa.Column("title", sa.String(length=60), nullable=False),
        sa.Column("upstream_model", sa.String(length=120), nullable=False),
        sa.Column("modality", sa.String(length=10), server_default="text", nullable=False),
        sa.Column("premium", sa.Boolean(), server_default=sa.false(), nullable=False),
        sa.Column("cost", sa.Integer(), server_default="1", nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default=sa.true(), nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default="100", nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )


def downgrade() -> None:
    op.drop_table("ai_models")
    op.drop_index("ix_ai_accounts_tier_priority", table_name="ai_accounts")
    op.drop_table("ai_accounts")
