#!/usr/bin/env bash
# Atomic release to the flashbot production host — immutable bundle + blue/green dir swap.
#
# Runs from the LOCAL machine (git-bash) and orchestrates the server over `ssh flashbot`.
# It NEVER prints the server .env or any secret. It hard-ABORTs on config drift, low disk,
# manifest/dist mismatch, or any failed verification, preserves the previous release, and
# prints exact rollback.
#
# The release ARTIFACT is NOT a byte-identical Git tree: it is the exact $REF source tree
# (forced LF) PLUS locally-built frontend assets (miniapp/dist, admin/dist) that are NOT in
# Git (they are .gitignore'd, generated by `vite build`). A RELEASE_MANIFEST.txt records the
# source SHA, build metadata, and a SHA-256 over each dist tree so the server can verify the
# shipped assets. The frontend is built LOCALLY (the prod host has no node/npm) — there is NO
# server-side `npm ci`/`npm run build`.
#
#   Usage:  bash scripts/atomic_release.sh [REF] [--dry-run] [--build-only]
#   REF defaults to fa654ba.
#   --dry-run     prints every command/remote step and changes NOTHING (no local build either).
#   --build-only  runs the LOCAL build + manifest + bundle + bundle-verification, then STOPS
#                 before any ssh/scp (no server contact) — for offline validation.
#
# Hard gates (each exits non-zero, no masking):
#   * config drift          — live Dockerfile/compose/Caddyfile must match the bundle (sha256; ABORT)
#   * manifest/dist integrity— manifest source_sha == $REF, both dist non-empty, dist sha256 match
#   * disk >= 7 GB           — checked before the swap/build path AND again right before docker build
#   * alembic == 0042 before swap; == 0044 after; 4 new indexes VALID; all app containers healthy;
#     smoke test passes      — any failure exits non-zero.
# No prune / cleanup is ever run on production. The frontend build happens locally, not on prod.
set -euo pipefail

# ---- args -------------------------------------------------------------------------------
REF="fa654ba"; DRY=0; BUILD_ONLY=0
for a in "$@"; do
  case "$a" in
    --dry-run)    DRY=1 ;;
    --build-only) BUILD_ONLY=1 ;;
    -*) echo "unknown flag: $a" >&2; exit 64 ;;
    *)  REF="$a" ;;
  esac
done

SSH_HOST="flashbot"
APP_DIR="/home/ubuntu/CHATGPTFLASHBOT"
REL_ROOT="/home/ubuntu/releases"
COMPOSE="docker compose -f docker-compose.yml -f docker-compose.prod.yml"
APP_SERVICES="migrate api bot worker beat"   # ONLY these are (re)built/recreated; caddy separate
DRIFT_FILES="Dockerfile docker-compose.yml docker-compose.prod.yml Caddyfile"
FRONTENDS="miniapp admin"                     # each has package-lock.json + `vite build` -> dist/
MIN_FREE_GB=7
EXPECT_CUR="0042_search_model"
EXPECT_HEAD="0044_missing_model_indexes"

TS="$(date +%Y%m%d-%H%M%S)"
SHORT="$(git rev-parse --short "$REF")"
FULL="$(git rev-parse "$REF")"
BUNDLE="release-${SHORT}.tar.gz"
STAGE="${REL_ROOT}/${SHORT}-${TS}"
MANIFEST="RELEASE_MANIFEST.txt"

WORK=""
cleanup(){ if [[ -n "$WORK" && -d "$WORK" && "${KEEP_WORK:-0}" -eq 0 ]]; then rm -rf "$WORK"; fi; }
trap cleanup EXIT

say(){ printf '\n=== %s ===\n' "$*"; }

# ssh_do <description> <remote-command>: returns the remote exit code (0 in dry-run).
ssh_do(){
  echo "  [remote] $1"
  if [[ "$DRY" -eq 1 ]]; then
    printf '    DRY: ssh %s <<CMD\n%s\nCMD\n' "$SSH_HOST" "$2"
    return 0
  fi
  ssh -o ConnectTimeout=30 "$SSH_HOST" "$2"
}

# Content-hash recipes: hash over "path\n<64-hex content sha>\n" for the selected files, sorted by
# path. `cut -c1-64` takes ONLY the hex digest, so it is immune to sha256sum's text/binary marker
# (' *' on Windows/msys vs two-space on Linux) — the SAME digest is produced locally and on the
# server. Run via `eval` locally (single source of truth) and interpolated verbatim into the ssh
# command remotely (bash does not re-expand a substituted variable's value, so $f stays a server var).
# shellcheck disable=SC2016  # $f is a server-side var, must stay literal (single quotes intentional)
REMOTE_SRC_HASH='find . -type f ! -path "./miniapp/dist/*" ! -path "./admin/dist/*" ! -name "RELEASE_MANIFEST.txt" ! -path "./.git/*" ! -path "*/node_modules/*" ! -path "./.env" ! -path "./.env.staging" -print0 | LC_ALL=C sort -z | while IFS= read -r -d "" f; do printf "%s\n" "$f"; sha256sum < "$f" | cut -c1-64; done | sha256sum | cut -c1-64'
# shellcheck disable=SC2016  # $f is a server-side var, must stay literal (single quotes intentional)
REMOTE_DIST_HASH='find dist -type f -print0 | LC_ALL=C sort -z | while IFS= read -r -d "" f; do printf "%s\n" "$f"; sha256sum < "$f" | cut -c1-64; done | sha256sum | cut -c1-64'
src_tree_hash(){  ( cd "$1" && eval "$REMOTE_SRC_HASH"  ); }
dist_tree_hash(){ ( cd "$1" && eval "$REMOTE_DIST_HASH" ); }

# --- these SQL/psql snippets run on the server; server-side $VARs are escaped as \$ ---
# SELECT1_Q / ALEMBIC_Q share the EXACT same shell+psql quoting path, so the read-only
# SELECT-1 preflight actually exercises the quoting the later gates depend on.
PSQL='docker exec chatgptflashbot-postgres-1 sh -lc'
ALEMBIC_Q="\"psql -U \\\$POSTGRES_USER -d \\\$POSTGRES_DB -tAc \\\"select version_num from alembic_version\\\"\""
SELECT1_Q="\"psql -U \\\$POSTGRES_USER -d \\\$POSTGRES_DB -tAc \\\"select 1\\\"\""

say "0. Preflight (local)"
git rev-parse --verify "${REF}^{commit}" >/dev/null
command -v node >/dev/null || { echo '>>> ABORT: local node not found (frontend is built locally).'; exit 10; }
command -v npm  >/dev/null || { echo '>>> ABORT: local npm not found (frontend is built locally).'; exit 10; }
echo "  REF=$REF short=$SHORT full=$FULL ts=$TS dry_run=$DRY build_only=$BUILD_ONLY min_free=${MIN_FREE_GB}GB"
echo "  local node=$(node -v) npm=$(npm -v)"

if [[ "$BUILD_ONLY" -eq 0 ]]; then
  say "0.5 Read-only quoting preflight — SELECT 1 via the EXACT PSQL/quoting path (no writes)"
  if ! ssh_do "psql shell-quoting check (SELECT 1)" "
    out=\$($PSQL $SELECT1_Q | tr -d '[:space:]')
    echo \"select1=\$out\"; [ \"\$out\" = '1' ]
  "; then
    echo '>>> ABORT: psql/shell quoting preflight failed (SELECT 1 did not return 1).'
    echo '>>> Later alembic/index gates use the same quoting — fix quoting before any deploy.'
    exit 12
  fi
fi

say "1. Build release artifact LOCALLY (exact $REF source, forced LF, + built frontend dist + manifest)"
# core.autocrlf=false + core.eol=lf pin LF regardless of the Windows global git config, so the
# SOURCE tree stays byte-for-byte $REF (blobs are LF) and never trips the config-drift gate.
if [[ "$DRY" -eq 1 ]]; then
  cat <<DRYBUILD
  DRY: WORK=\$(mktemp -d); SRC=\$WORK/src
       git -c core.autocrlf=false -c core.eol=lf archive --format=tar $REF | tar -x -C \$SRC   # exact source, LF
       for d in $FRONTENDS: ( cd \$SRC/\$d && npm ci && npm run build )                         # lockfile-accurate local build
       rm -rf \$SRC/*/node_modules                                                              # never ship node_modules
       write \$SRC/$MANIFEST (source_sha=$FULL, built_at, node, npm, <dist sha256 x2>)
       tar -C \$SRC --exclude node_modules/.git/.env* -czf $BUNDLE .                            # source + dist + manifest
       sha256sum $BUNDLE > ${BUNDLE}.sha256
       verify_bundle: source == $REF tracked tree, both dist present+nonempty, manifest present, NO .env/.git/node_modules
DRYBUILD
else
  WORK="$(mktemp -d)"; SRC="$WORK/src"; PRISTINE="$WORK/pristine"; mkdir -p "$SRC" "$PRISTINE"
  echo "  workspace: $WORK"
  # Two independent extractions of the EXACT $REF tree (forced LF). PRISTINE is never touched by npm;
  # SRC is where we build. Comparing their content-hashes proves the build didn't mutate any source.
  git -c core.autocrlf=false -c core.eol=lf archive --format=tar "$REF" | tar -x -C "$SRC"
  git -c core.autocrlf=false -c core.eol=lf archive --format=tar "$REF" | tar -x -C "$PRISTINE"
  pristine_src_hash="$(src_tree_hash "$PRISTINE")"
  echo "  pristine source_tree_sha256=$pristine_src_hash"
  for d in $FRONTENDS; do
    echo "  -- local build: $d (npm ci && npm run build) --"
    ( cd "$SRC/$d" && npm ci && npm run build )
    test -s "$SRC/$d/dist/index.html" || { echo ">>> ABORT: $d/dist/index.html missing/empty after build."; exit 11; }
  done
  rm -rf "$SRC"/*/node_modules                       # npm ci created these; never ship them
  # ZERO-TRUST: the built tree's SOURCE content (excluding dist + manifest) must be byte-identical to
  # pristine $REF. A single changed source byte here aborts BEFORE any bundle is created.
  built_src_hash="$(src_tree_hash "$SRC")"
  echo "  built    source_tree_sha256=$built_src_hash"
  if [ "$built_src_hash" != "$pristine_src_hash" ]; then
    echo ">>> ABORT: local build mutated the source tree (content-hash mismatch vs pristine $REF)."
    echo ">>>        pristine=$pristine_src_hash built=$built_src_hash — refusing to bundle."
    exit 14
  fi
  mh="$(dist_tree_hash "$SRC/miniapp")"
  ah="$(dist_tree_hash "$SRC/admin")"
  {
    echo "source_ref=$REF"
    echo "source_sha=$FULL"
    echo "source_tree_sha256=$pristine_src_hash"
    echo "built_at=$(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo "built_node=$(node -v)"
    echo "built_npm=$(npm -v)"
    echo "miniapp_dist_sha256=$mh"
    echo "admin_dist_sha256=$ah"
  } > "$SRC/$MANIFEST"
  echo "  manifest written: source_sha=$FULL source_tree=$pristine_src_hash miniapp_dist=$mh admin_dist=$ah"
  BUNDLE_ABS="$PWD/$BUNDLE"
  # Exclude only actual secrets + build junk. NOTE: tracked `.env.example` / `.env.staging.example`
  # ARE part of the source tree and MUST ship — so do NOT use a broad `.env.*` glob.
  ( cd "$SRC" && tar --exclude='./.git' --exclude='*/node_modules' --exclude='./.env' --exclude='./.env.staging' \
                     -czf "$BUNDLE_ABS" . )
  sha256sum "$BUNDLE" | tee "${BUNDLE}.sha256"

  # ---- verify the bundle we just built (step-5 tar checks) ----
  echo "  -- verify bundle contents --"
  list="$(tar tzf "$BUNDLE" | sed 's#^\./##')"
  if printf '%s\n' "$list" | grep -Eq '(^|/)node_modules/|(^|/)\.git/'; then
    echo ">>> ABORT: bundle contains node_modules/.git."; exit 13; fi
  # real secret env files only ( .env, .env.staging, ... ) — but NOT *.example templates
  env_bad="$(printf '%s\n' "$list" | grep -E '(^|/)\.env(\.[A-Za-z0-9_-]+)?$' | grep -vE '\.example$' || true)"
  if [ -n "$env_bad" ]; then echo ">>> ABORT: bundle contains a real env file:"; printf '  %s\n' "$env_bad"; exit 13; fi
  for d in $FRONTENDS; do
    printf '%s\n' "$list" | grep -q "^$d/dist/index.html$" || { echo ">>> ABORT: $d/dist missing in bundle."; exit 13; }
  done
  printf '%s\n' "$list" | grep -qx "$MANIFEST" || { echo ">>> ABORT: manifest missing in bundle."; exit 13; }
  # source PATHS in the bundle must equal EXACTLY the $REF tracked tree (catches extra/missing files;
  # byte-identical CONTENT is separately proven by the source_tree_sha256 pristine==built check above).
  git -c core.autocrlf=false ls-tree -r --name-only "$REF" | LC_ALL=C sort > "$WORK/expected_src.txt"
  printf '%s\n' "$list" | grep -vE "^(miniapp/dist/|admin/dist/|$MANIFEST$)" | grep -v '/$' | grep -v '^$' \
    | LC_ALL=C sort > "$WORK/bundle_src.txt"
  if ! diff -q "$WORK/expected_src.txt" "$WORK/bundle_src.txt" >/dev/null; then
    echo ">>> ABORT: bundle source paths != $REF tracked tree. Differences:"
    diff "$WORK/expected_src.txt" "$WORK/bundle_src.txt" | head -40
    exit 13
  fi
  # final: the bundled source content-hash must still equal pristine $REF (belt-and-suspenders after tar)
  mkdir -p "$WORK/unpacked"
  tar xzf "$BUNDLE" -C "$WORK/unpacked"
  bundled_src_hash="$(src_tree_hash "$WORK/unpacked")"
  if [ "$bundled_src_hash" != "$pristine_src_hash" ]; then
    echo ">>> ABORT: bundled source content-hash != pristine $REF (pristine=$pristine_src_hash bundled=$bundled_src_hash)."
    exit 13
  fi
  echo "  bundle OK: source CONTENT-hash == pristine $REF ($pristine_src_hash); paths match tracked tree;"
  echo "            both dist present+nonempty; manifest present; no real .env/.git/node_modules"
fi

if [[ "$BUILD_ONLY" -eq 1 ]]; then
  KEEP_WORK=1
  say "BUILD-ONLY complete — no server contact. Artifact: $BUNDLE (+ .sha256). Workspace kept: ${WORK:-n/a}"
  exit 0
fi

say "2. Deliver bundle to server staging area"
ssh_do "ensure releases dir" "mkdir -p '$REL_ROOT/incoming'"
if [[ "$DRY" -eq 1 ]]; then
  echo "  DRY: scp $BUNDLE ${BUNDLE}.sha256 $SSH_HOST:$REL_ROOT/incoming/"
else
  scp "$BUNDLE" "${BUNDLE}.sha256" "$SSH_HOST:$REL_ROOT/incoming/"
fi

say "3. Stage: verify checksum + extract into SAME-filesystem dir"
ssh_do "checksum + extract" "
  set -e
  ( cd '$REL_ROOT/incoming' && sha256sum -c '${BUNDLE}.sha256' )
  mkdir -p '$STAGE'
  tar xzf '$REL_ROOT/incoming/$BUNDLE' -C '$STAGE'
  test -f '$STAGE/Dockerfile' && test -f '$STAGE/docker-compose.prod.yml' && echo 'staging tree OK'
"

say "3.5 CONFIG DRIFT HARD-GATE (live vs bundle by sha256; file CONTENTS never printed — may hold secrets)"
if ! ssh_do "fingerprint prod deploy config vs bundle" "
  drift=0
  for f in $DRIFT_FILES; do
    if [ ! -f '$APP_DIR'/\"\$f\" ]; then echo \"### MISSING on server: \$f\"; drift=1; continue; fi
    if ! cmp -s '$APP_DIR'/\"\$f\" '$STAGE'/\"\$f\"; then
      live=\$(sha256sum < '$APP_DIR'/\"\$f\" | cut -c1-16)
      bund=\$(sha256sum < '$STAGE'/\"\$f\" | cut -c1-16)
      echo \"### DRIFT: \$f (live sha=\$live bundle sha=\$bund) ###\"; drift=1
    fi
  done
  [ \"\$drift\" -eq 0 ] && echo 'no drift — deploy config matches Git' || exit 20
"; then
  echo ">>> ABORT: production Dockerfile/compose/Caddyfile drift from Git (differing files listed above)."
  echo ">>> Contents are NOT shown (possible secrets). Migrate manual server changes into Git first, then re-run."
  exit 20
fi

say "3.6 MANIFEST + FULL SOURCE + FRONTEND DIST INTEGRITY (recomputed on server; BEFORE .env copy)"
# Runs strictly before phase 4 (.env copy), so the staging tree here is pure bundle content (no .env
# yet) — the recomputed source_tree_sha256 covers the ENTIRE exact source, not just dist.
if ! ssh_do "verify manifest + source_tree + dist sha256 (recompute on server)" "
  set -e
  test -f '$STAGE/$MANIFEST' || { echo 'manifest MISSING'; exit 1; }
  src=\$(grep '^source_sha=' '$STAGE/$MANIFEST' | cut -d= -f2)
  [ \"\$src\" = '$FULL' ] || { echo \"manifest source_sha=\$src != $FULL\"; exit 1; }
  est=\$(grep '^source_tree_sha256=' '$STAGE/$MANIFEST' | cut -d= -f2)
  em=\$(grep  '^miniapp_dist_sha256=' '$STAGE/$MANIFEST' | cut -d= -f2)
  ea=\$(grep  '^admin_dist_sha256='   '$STAGE/$MANIFEST' | cut -d= -f2)
  for d in $FRONTENDS; do test -s \"$STAGE/\$d/dist/index.html\" || { echo \"\$d/dist missing/empty\"; exit 1; }; done
  st=\$( cd '$STAGE'        && $REMOTE_SRC_HASH )
  mh=\$( cd '$STAGE/miniapp' && $REMOTE_DIST_HASH )
  ah=\$( cd '$STAGE/admin'   && $REMOTE_DIST_HASH )
  echo \"source_tree computed=\$st manifest=\$est\"
  echo \"miniapp_dist computed=\$mh manifest=\$em\"
  echo \"admin_dist   computed=\$ah manifest=\$ea\"
  [ \"\$st\" = \"\$est\" ] || { echo 'FULL SOURCE content-hash mismatch'; exit 1; }
  [ \"\$mh\" = \"\$em\" ] && [ \"\$ah\" = \"\$ea\" ]
"; then
  echo '>>> ABORT: manifest / full-source / frontend-dist integrity check failed. Nothing swapped.'
  exit 24
fi

say "4. Carry over existing .env (copy only — contents NEVER printed; stays only on the server)"
ssh_do "copy .env, verify by SIZE only" "
  set -e
  test -s '$APP_DIR/.env'
  cp -p '$APP_DIR/.env' '$STAGE/.env'
  test -s '$STAGE/.env' && echo \".env carried (size=\$(stat -c%s '$STAGE/.env') bytes; contents not shown)\"
"

say "5. DISK HARD-STOP #1 (>= ${MIN_FREE_GB} GB) — staging headroom before the swap/build path"
if ! ssh_do "disk check #1" "
  avail=\$(df -BG --output=avail / | tail -1 | tr -dc 0-9)
  echo \"free_GB=\$avail (min=${MIN_FREE_GB})\"
  [ \"\$avail\" -ge ${MIN_FREE_GB} ]
"; then
  echo ">>> ABORT: < ${MIN_FREE_GB} GB free. No prune performed. Nothing swapped."
  exit 21
fi

say "6. Validate merged compose in staging (config -q — no secret output)"
ssh_do "compose config -q" "cd '$STAGE' && $COMPOSE config -q && echo 'compose config valid'"

say "7. Pre-swap safety: prod alembic MUST be $EXPECT_CUR"
if ! ssh_do "assert alembic == $EXPECT_CUR" "
  cur=\$($PSQL $ALEMBIC_Q | tr -d '[:space:]')
  echo \"alembic_current=\$cur\"
  [ \"\$cur\" = '$EXPECT_CUR' ]
"; then
  echo ">>> ABORT: prod alembic is not $EXPECT_CUR. Nothing swapped."
  exit 22
fi

say "8. DISK HARD-STOP #2 (>= ${MIN_FREE_GB} GB) — right before swap + docker build"
if ! ssh_do "disk check #2" "
  avail=\$(df -BG --output=avail / | tail -1 | tr -dc 0-9)
  echo \"free_GB=\$avail (min=${MIN_FREE_GB})\"
  [ \"\$avail\" -ge ${MIN_FREE_GB} ]
"; then
  echo ">>> ABORT: < ${MIN_FREE_GB} GB free before docker build. No prune. Nothing swapped."
  exit 23
fi

say "9. ATOMIC SWAP (preserve previous) + provenance marker + auto-recovery"
if ! ssh_do "swap current<->staging (recover on failure)" "
  set -e
  mv '$APP_DIR' '${APP_DIR}.prev.${TS}'
  if ! mv '$STAGE' '$APP_DIR'; then
    echo '### SWAP FAILED: second mv failed — restoring previous current dir ###'
    if mv '${APP_DIR}.prev.${TS}' '$APP_DIR'; then
      echo '### RECOVERED: original current dir restored; nothing rebuilt ###'
    else
      echo '### CRITICAL: restore ALSO failed — current is at ${APP_DIR}.prev.${TS}; manual fix required ###'
    fi
    exit 40
  fi
  printf '%s\n' '$FULL' > '$APP_DIR/.DEPLOYED_SHA'
  echo \"swapped: prev=${APP_DIR}.prev.${TS} active=$APP_DIR sha=$FULL\"
"; then
  echo '>>> ABORT: atomic swap failed. Previous release auto-restored (see remote output). Nothing rebuilt.'
  exit 40
fi

say "10. Rebuild + recreate ONLY app services ($APP_SERVICES); caddy separate; DB/cache/minio untouched"
ssh_do "build app images" "cd '$APP_DIR' && $COMPOSE build $APP_SERVICES"
ssh_do "up -d app services (migrate applies 0043/0044 first, fail-closed)" "cd '$APP_DIR' && $COMPOSE up -d $APP_SERVICES"
ssh_do "force-recreate caddy for new dist/Caddyfile" "cd '$APP_DIR' && $COMPOSE up -d --force-recreate caddy"

say "11. VERIFY — any failure exits non-zero (no masking)"
if ! ssh_do "alembic head == $EXPECT_HEAD" "
  cur=\$($PSQL $ALEMBIC_Q | tr -d '[:space:]')
  echo \"alembic_current=\$cur\"; [ \"\$cur\" = '$EXPECT_HEAD' ]
"; then echo ">>> FAIL: migrations not at $EXPECT_HEAD"; exit 30; fi

if ! ssh_do "4 new indexes present + VALID" "
  n=\$($PSQL \"psql -U \\\$POSTGRES_USER -d \\\$POSTGRES_DB -tAc \\\"select count(*) from pg_class c join pg_index i on i.indexrelid=c.oid where c.relname in ('ix_users_bot_id','ix_gifts_buyer_id','ix_gifts_redeemed_by','ix_contest_entries_user_id') and i.indisvalid\\\"\" | tr -d '[:space:]')
  echo \"valid_new_indexes=\$n (expect 4)\"; [ \"\$n\" = '4' ]
"; then echo ">>> FAIL: missing/invalid new index (run DROP INDEX CONCURRENTLY IF EXISTS + re-migrate)"; exit 31; fi

if ! ssh_do "no unhealthy containers + app services running" "
  bad=\$(docker ps --filter 'health=unhealthy' --format '{{.Names}}')
  [ -z \"\$bad\" ] || { echo \"UNHEALTHY: \$bad\"; exit 1; }
  for s in api bot worker beat; do
    st=\$(docker inspect -f '{{.State.Status}}' chatgptflashbot-\$s-1 2>/dev/null)
    echo \"\$s=\$st\"; [ \"\$st\" = 'running' ] || exit 1
  done
"; then echo ">>> FAIL: unhealthy or non-running app container"; exit 32; fi

# Prod api is published to 127.0.0.1:8000 (docker-compose.prod.yml `api: ports: !reset []` keeps it
# loopback-only). Pass the port explicitly and use 127.0.0.1 (NOT localhost) to avoid IPv6 ::1 resolve.
if ! ssh_do "smoke test (BASE_URL=http://127.0.0.1:8000)" "cd '$APP_DIR' && BASE_URL=http://127.0.0.1:8000 bash scripts/smoke_test.sh"; then
  echo ">>> FAIL: smoke test failed"; exit 33
fi

ssh_do "recent app logs (tail, informational)" "cd '$APP_DIR' && $COMPOSE logs --tail=30 api bot worker" || true

cat <<ROLLBACK

======================  DEPLOY OK  ·  ROLLBACK (run on the server if needed later)  ======================
# APP rollback (0043/0044 additive → old code runs fine on the indexed schema; no DB downgrade):
  mv $APP_DIR ${APP_DIR}.failed.${TS} && mv ${APP_DIR}.prev.${TS} $APP_DIR
  cd $APP_DIR && $COMPOSE build $APP_SERVICES && $COMPOSE up -d $APP_SERVICES && $COMPOSE up -d --force-recreate caddy
# MIGRATION rollback (only if schema must revert; reversible DROP INDEX CONCURRENTLY):
  cd $APP_DIR && $COMPOSE run --rm migrate alembic downgrade $EXPECT_CUR
# DB restore (LAST RESORT — data corruption only):
  gunzip -c ~/predeploy-backup-fa654ba-20260713-195247.sql.gz | docker exec -i chatgptflashbot-postgres-1 sh -lc 'psql -U \$POSTGRES_USER -d \$POSTGRES_DB'
=========================================================================================================
ROLLBACK
